### ISSUE TITLE
Questions about github-proxy

### ISSUE THREAD

**Issue by maoo** [pGrovesy/github-proxy#3]
@pGrovesy , thanks a lot for sharing this code, the idea sounds too good to be true, and I'm more than happy to help with code.

Before getting into technology, I'd like to ask you some questions about the desired solution.

I see that the roadmap mentions to `Become a "true" proxy that can be set via "git config http.proxy...."`; I guess this solution will have to work around TLS end-to-end encryption in some way, which would probably force the use of some unconventional libraries/computation.

I wonder if - instead - we could introduce a simple naming convention to generate the Git endpoint that is read by the server, so that developers get easily used to it.

For example, Git remotes can be defined as `git://<github-proxy-host>/gh/<github org or user>/<github repo name>.git`, so that the server can extract `<github org or user>` and `<github repo name>` and be able to dispatch incoming commands (if/when validation occurs and is passed).

Another confirmation is that this proxy will only manage Git activity.... and therefore:
- It could actually be called git-proxy
- GitHub Issues, Pull Requests, Discussions and other way of collaborations that are not done via Git commit/push, are out of scope for this project

Is that correct?

TY!

**Comment by pGrovesy** [comment]
So right now it works by setting up a remote which assumes the *target* is https://{host}/{project}/{repo} and is setup locally as 'remote' e.g. 'git remote origin http://{proxy}/{project}/{repo}.git

We would have to decide if we just stick with it being a 'remote' or we decide to support being a 'proxy' - "git config --global --add HTTP.proxy HTTP://{git-proxy}"

SSH is another topic, right now supporting Http and Https

**Comment by maoo** [comment]
> So right now it works by setting up a remote which assumes the target is https://{host}/{project}/{repo} and is setup locally as 'remote' e.g. 'git remote origin http://{proxy}/{project}/{repo}.git

Got it now (also looked at the code, it's clearer now). So am I right assuming that there will be a way to configure the proxy so that `{host}` is `github.com` , allowing us to - for example - do `git clone https://localhost:3001/finos/open-developer-platform.git` ?

> We would have to decide if we just stick with it being a 'remote' or we decide to support being a 'proxy' - "git config --global --add HTTP.proxy HTTP://{git-proxy}"

I'd vote for both; I kinda like the first approach too, as it's less hidden; you can always do `git remote -v` and see the Proxy in the URL, which makes it clear that you're not communicating directly with the github.com (upstream) endpoint.

I agree that some firms may find the proxy setup easier to integrate, so I'm in favour of this approach too; could it be a configuration switch?

**Comment by pGrovesy** [comment]
> Got it now (also looked at the code, it's clearer now). So am I right assuming that there will be a way to configure the proxy so that `{host}` is `github.com` , allowing us to - for example - do `git clone https://localhost:3001/finos/open-developer-platform.git` ?

Correct and yes I think both styles are good tool have- I'll put some more of a roadmap together in the next day -- feature suggestions welcome, audit-log-synchs, synch vs asnych pushes etc
