### ISSUE TITLE
Project Installation Test Instructions

### ISSUE THREAD

**Issue by mcleo-d** [pGrovesy/github-proxy#7]
### Description
The project installation test instructions are written from the profile point of view of @pGrovesy on GitHub. 

This means login credentials are requested when running `git commit` and `git push origin` after cloning from `https://github.com/pGrovesy/`

### Potential Solution
Amend the installation test instructions to add the following steps for local development, which is likely to be different from the final deployment and development scenario.

1. Fork `test-allowed-repo` and `test-banned-repo` to your development GitHub profile
2. Run `git clone http://localhost:3000/<fork>/test-allowed-repo`
3. Run `git clone http://localhost:3000/<fork>/test-banned-repo`
4. Edit the README.md file in `test-allowed-repo` and `test-banned-repo` repo. 
5. Within both projects, run the `git` instructions highlighted in `push.bat`

From that point forward the success and error criteria should be the same.

### Next Steps

Let me know if you agree with the approach above and I'll develop and test locally before raising a PR to amend.

👍

**Comment by pGrovesy** [comment]
Looks good to me - I think the user will need to edit the config.json file

.. I may look at an override file that is in the .gitignore
(user-settings.json) so the main config.json isn't modified

**Comment by mcleo-d** [comment]
No problem. Let me take this up to the cloning scenario. I'll let you know if I was able to include the override in the PR 👍

**Comment by mcleo-d** [comment]
@pGrovesy - I've closed this issue now #8 has been merged. Feel free to reopen if there are tasks outstanding.
